### ISSUE TITLE
Cannot compile (Windows)

### ISSUE THREAD

**Issue by caecos** [VCVRack/Fundamental#49] opened 2018-07-10 00:05 UTC
$ make
g++ -Wsuggest-override -std=c++11 -Idep/include -DSLUG=Fundamental -fPIC -I../../include -I../../dep/include -DVERSION=0.6.1 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/Fundamental.cpp.o src/Fundamental.cpp
g++ -Wsuggest-override -std=c++11 -Idep/include -DSLUG=Fundamental -fPIC -I../../include -I../../dep/include -DVERSION=0.6.1 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/Delay.cpp.o src/Delay.cpp
g++ -Wsuggest-override -std=c++11 -Idep/include -DSLUG=Fundamental -fPIC -I../../include -I../../dep/include -DVERSION=0.6.1 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/VCF.cpp.o src/VCF.cpp
src/VCF.cpp: In member function 'void LadderFilter::process(float, float)':
src/VCF.cpp:35:3: error: 'stepRK4' was not declared in this scope
   stepRK4(0.f, dt, state, 4, [&](float t, const float y[], float dydt[]) {
   ^~~~~~~
src/VCF.cpp:35:3: note: suggested alternative:
In file included from src/VCF.cpp:4:0:
../../include/dsp/ode.hpp:58:6: note:   'rack::ode::stepRK4'
 void stepRK4(float t, float dt, float x[], int len, F f) {
      ^~~~~~~
make: *** [../../compile.mk:65: build/src/VCF.cpp.o] Error 1

**Comment by marcoose777** [comment] 2018-07-10 00:15
Me too on Linux, luckily it is very simple. Read the g++ output first then:

Change line 35 of VCF.cpp in the path [where I installed Rack]/Rack/plugins/Fundamental/src/VCF.cpp, from:
`stepRK4(0.f, dt, state, 4, [&](float t, const float y[], float dydt[]) {`
to `rack::ode::stepRK4(0.f, dt, state, 4, [&](float t, const float y[], float dydt[]) {`

Clever g++ even tells you where the issue is, how neat is that. If your unsure, I've just specified the namespace for the ode solver functions that stepRK4 (4th Order Runge-Kutta method) is a member of. Execute make again, and it should finish off, as it did for me

**Comment by AndrewBelt** [comment] 2018-07-10 23:15
Fixed in baa041b

**Closed by AndrewBelt** 2018-07-10 23:15 UTC
