### ISSUE TITLE
sometimes textures displayed compressed

### ISSUE THREAD

**Issue by miguel-negrao** [VCVRack/Fundamental#60] opened 2019-03-16 11:34 UTC
![Captura de ecrã de 2019-03-16 11-32-50](https://user-images.githubusercontent.com/382777/54474662-6936f800-47df-11e9-8a86-82dc01a8aa90.png)

v0.6.2c
Linux Debian 9

Usually restarting program solves the issue.

**Comment by AndrewBelt** [comment] 2019-03-18 00:14
Duplicate of https://github.com/VCVRack/Rack/issues/461

**Closed by AndrewBelt** 2019-03-18 00:14 UTC
