### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by shimpe** [VCVRack/Fundamental#24] opened 2017-12-31 09:50 UTC
Most plugins fail to build with error messages like the following:

src/SEQ3.cpp:109:7: error: ‘void SEQ3::onReset()’ marked ‘override’, but does not override
  void onReset() override {
       ^~~~~~~
src/SEQ3.cpp:115:7: error: ‘void SEQ3::onRandomize()’ marked ‘override’, but does not override
  void onRandomize() override {
       ^~~~~~~~~~~

**Comment by shimpe** [comment] 2017-12-31 10:33
ok, it does build after checking out the most recent tags. 
Maybe best to add a warning to the README files?

**Comment by AndrewBelt** [comment] 2017-12-31 14:18
Duplicate of https://github.com/VCVRack/Fundamental/issues/23

Will add to README

**Closed by AndrewBelt** 2017-12-31 14:18 UTC
